######################################################################
# Automatically generated by qmake (3.0) ??? ?? 11 15:04:33 2014
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .
CONFIG += console debug
CONFIG -= moc
CONFIG += c++11
# QMAKE_CXXFLAGS += -std=c++11

# Input
SOURCES += hello.cpp
