######################################################################
# Automatically generated by qmake (3.0) ??? ?? 11 15:04:33 2014
######################################################################

TEMPLATE = app
TARGET = designer
INCLUDEPATH += .
CONFIG += debug
QT += widgets

# Input
HEADERS += name_dialog.h
FORMS += name.ui
SOURCES += main.cpp name_dialog.cpp
