######################################################################
# Automatically generated by qmake (3.0) ??? ?? 11 15:04:33 2014
######################################################################

TEMPLATE = app
TARGET = tcp_echo_server
INCLUDEPATH += .
CONFIG += console debug
CONFIG -= moc
CONFIG += c++11
LIBS += -lboost_thread -lboost_system -lboost_date_time
# QMAKE_CXXFLAGS += -std=c++11

win32 {
  LIBS += -lws2_32
}

# Input
SOURCES += tcp_echo_server.cpp
