######################################################################
# Automatically generated by qmake (3.0) ??? ?? 11 15:04:33 2014
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .
CONFIG += debug
QT += widgets

# Input
SOURCES += hello.cpp
